# Generated by Django 5.1.6 on 2025-02-28 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_dashboard', 'Can view admin dashboard'), ('can_manage_users', 'Can manage user accounts'), ('can_edit_profile', 'Can edit user profile')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
